// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpb9RzS35CVl8e6vD7qhWz77qAKtDUn4E',
    appId: '1:53695885316:web:4e439a4d18baf55b0d0551',
    messagingSenderId: '53695885316',
    projectId: 'spend-wise-b74c7',
    authDomain: 'spend-wise-b74c7.firebaseapp.com',
    storageBucket: 'spend-wise-b74c7.firebasestorage.app',
    measurementId: 'G-7B6G12709Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCmsW_iekOxBMP7LwVyQbDJaLcyoXPu4A',
    appId: '1:53695885316:android:0571e8bed45039f60d0551',
    messagingSenderId: '53695885316',
    projectId: 'spend-wise-b74c7',
    storageBucket: 'spend-wise-b74c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQdZ-P3Enu9GNwUzC3beowDosxWNWR1os',
    appId: '1:53695885316:ios:84224f51b1d3a4610d0551',
    messagingSenderId: '53695885316',
    projectId: 'spend-wise-b74c7',
    storageBucket: 'spend-wise-b74c7.firebasestorage.app',
    iosBundleId: 'com.example.spendWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQdZ-P3Enu9GNwUzC3beowDosxWNWR1os',
    appId: '1:53695885316:ios:84224f51b1d3a4610d0551',
    messagingSenderId: '53695885316',
    projectId: 'spend-wise-b74c7',
    storageBucket: 'spend-wise-b74c7.firebasestorage.app',
    iosBundleId: 'com.example.spendWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpb9RzS35CVl8e6vD7qhWz77qAKtDUn4E',
    appId: '1:53695885316:web:990f9a57b6699f7c0d0551',
    messagingSenderId: '53695885316',
    projectId: 'spend-wise-b74c7',
    authDomain: 'spend-wise-b74c7.firebaseapp.com',
    storageBucket: 'spend-wise-b74c7.firebasestorage.app',
    measurementId: 'G-8YQMD916EC',
  );
}
